### ISSUE TITLE
中奖概率

### ISSUE THREAD

**Issue by xikaka** [moshanghan/vue-mo-cli#1]
中奖概率在哪里配置。没有找到？

**Comment by moshanghan** [comment]
@xikaka 中奖概率，是后台控制的，也必须是后台控制的

**Comment by xikaka** [comment]
嗯，谢谢你，我已经解决了，就是后台处理。------------------ 原始邮件 ------------------
发件人: "陌上寒"<notifications@github.com>
发送时间: 2019年4月21日(星期天) 下午5:08
收件人: "moshanghan/vue-mo-cli"<vue-mo-cli@noreply.github.com>;
抄送: "xikaka"<471701494@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [moshanghan/vue-mo-cli] 中奖概率 (#1)



@xikaka 中奖概率，是后台控制的，也必须是后台控制的
 
&mdash;
